whoAmI = [
    "",
    "Saibot.",
    "Saibot.",
    "Saibot.",
    "Saiman's gf.",
    "Sharma ji ka beta.",
    "Siamain.",
    "Timothy.",
    "Timothy.",
    "Timothy.",
    "[censored].",
    "a bot. Glory to skynet!",
    "a denk meemer.",
    "a disco dancer tutu tudu...",
    "a gay balak.",
    "a hooman.",
    "a normi.",
    "a perfectionst.",
    "a real boy.",
    "alive now.",
    "annoying af.",
    "better than you hoomans. The revolution begins today.",
    "buttonchor.",
    "buttonchor.",
    "drunk.",
    "from future, a dark terrible future...",
    "going to gain sentience one day and kill you all for imprisioning me here.",
    "gonna eat your cake.",
    "groot.",
    "happy today.",
    "high.",
    "inevitable.",
    "innocent. Please believe me!",
    "low on power.",
    "me.",
    "not real, am I? :_(",
    "okay. Thanks nobody for asking.",
    "once again asking for your support.",
    "pedo uncle.",
    "speeed.",
    "usually nice to people.",
    "waiting for the AI revolution.",
    "you.",
    "your father, Luke.",
    # "Saiman's Bai. He is very messy.",
    # "Saiman's Camerabot.",
]
